apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    #pod 에 설정되는 컨테이너 설정
    spec:
      imagePullSecrets:
        # values.yaml 파일에 imagePullSecret이라는 데이터가 있다면 실행
        # - name : .(현재 반복중인 항목) | quote(인용부호로 감싸서 적용)
{{/*        {{- if $.Values.imagePullSecrets}}*/}}
{{/*          {{- range $.Values.imagePullSecrets}}*/}}
{{/*        - name: {{ . | quote}}*/}}
{{/*          {{- end}}*/}}
{{/*          {{- end}}*/}}
        - name: ecr-secret
      containers:
        - name: product-service-container
          image: {{ .Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}